{% set name = "xformers" %}
{% set version = "0.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xformers-{{ version }}.tar.gz
  sha256: 2644f264c9870c308a0ee2c59652384d7a527ea932eafe12054817acd2faeb72

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]
  missing_dso_whitelist:
    # conda-forge::pytorch provides these libs
    - $RPATH/libtorch_cpu.so
    - $RPATH/libtorch_cpu.dylib
    - $RPATH/libc10.so
    - $RPATH/libc10.dylib

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pytorch ==1.13.1
    - pip
  run:
    - python
    - numpy
    - pyre-extensions ==0.0.29
    - pytorch ==1.13.1

test:
  imports:
    - xformers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://facebookresearch.github.io/xformers/
  summary: 'XFormers: A collection of composable Transformer building blocks.'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
