context:
  version: "0.0.33.post2"
  build_number: 0
  cuda_build_string: cuda_${{ cuda_compiler_version | version_to_buildstring }}
  string_prefix: ${{ cuda_build_string if cuda_compiler_version != "None" else "cpu_" }}

package:
  name: xformers
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/x/xformers/xformers-${{ version }}.tar.gz
    sha256: 647ddf26578d2b8643230467ef1f0fbfef0bbe556a546bd27a70d4855d3433e1
  - url: https://raw.githubusercontent.com/NVIDIA/cutlass/main/LICENSE.txt
    sha256: 7bc733829f16663593865344541c6dcc433beb6b6b555c8f86a43e9b399993cf
    file_name: third_party/cutlass/LICENSE.txt
  - url: https://raw.githubusercontent.com/Dao-AILab/flash-attention/main/LICENSE
    sha256: 8c9ccb96c065e706135b6cbad279b721da6156e51f3a5f27c6b3329af9416d73
    file_name: third_party/flash-attention/LICENSE

build:
  number: ${{ build_number }}
  skip:
    - win
  string: ${{ string_prefix }}py${{ python | version_to_buildstring }}h${{ hash }}_${{ build_number }}
  script:
    file: build

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pytorch
        - if: cuda_compiler_version != "None"
          then:
            - cuda-driver-dev
            - cuda-cudart-dev
            - cuda-nvrtc-dev
            - cuda-nvtx-dev
            - cuda-nvml-dev
            - libcublas-dev
            - libcufft-dev
            - libcurand-dev
            - libcusolver-dev
            - libcusparse-dev
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - git
    - if: cuda_compiler_version != "None"
      then:
        - ${{ compiler('cuda') }}
        - cuda-version ==${{ cuda_compiler_version }}
  host:
    - python
    - pip
    - setuptools
    - ${{ "pytorch * cuda*" if cuda_compiler_version != "None" }}
    - ${{ "pytorch * cpu*" if cuda_compiler_version == "None" }}
    - pytorch
    - if: cuda_compiler_version != "None"
      then:
        - cuda-version ==${{ cuda_compiler_version }}
        - cuda-driver-dev
        - cuda-cudart-dev
        - cuda-nvrtc-dev
        - cuda-nvtx-dev
        - cuda-nvml-dev
        - libcublas-dev
        - libcufft-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
  run:
    - python
    - numpy
    - pyre-extensions >=0.0.29
    - ${{ "pytorch * cuda*" if cuda_compiler_version != "None" }}
    - ${{ "pytorch * cpu*" if cuda_compiler_version == "None" }}
    - if: cuda_compiler_version != "None"
      then:
        - cuda-driver-dev
  ignore_run_exports:
    # not identical to list of host deps; we do need cuda-cudart,
    # cuda-driver-dev & cuda-nvml-dev have no run-exports
    from_package:
      - if: cuda_compiler_version != "None"
        then:
          - cuda-nvrtc-dev
          - cuda-nvtx-dev
          - libcublas-dev
          - libcufft-dev
          - libcurand-dev
          - libcusolver-dev
          - libcusparse-dev

tests:
  - python:
      imports:
        - xformers
      pip_check: true
  - script:
      - python -m xformers.info

about:
  license: BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE
    - third_party/cutlass/LICENSE.txt
    - third_party/flash-attention/LICENSE
    - third_party/sputnik/LICENSE
  summary: "XFormers: A collection of composable Transformer building blocks."
  homepage: https://facebookresearch.github.io/xformers/
  repository: https://github.com/facebookresearch/xformers

extra:
  recipe-maintainers:
    - jan-janssen
    - h-vetinari
