github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 16GiB
build_platform:
  osx_arm64: osx_64
test: native_and_emulated
conda_build_tool: 'rattler-build'
conda_install_tool: pixi
