azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 16GiB
bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_build_tool: 'rattler-build'
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  timeout_minutes: 480
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
test: native_and_emulated
